# Generated by Django 5.1.1 on 2024-09-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_cad_usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuarios",
            name="idade",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
