# Generated by Django 5.1.1 on 2024-09-20 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_cad_usuarios", "0002_usuarios_idade"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Usuarios",
            new_name="Usuario",
        ),
    ]
